#!/usr/bin/env node

var opts = {
  // WARNING: By setting this environment variable, anyone on your network may
  // run arbitrary code in your browser and read arbitrary files in the working
  // directory of the open file!
  interface: process.env.INSTANT_MARKDOWN_OPEN_TO_THE_WORLD ? '0.0.0.0' : '127.0.0.1',
  allow_unsafe_content: process.env.INSTANT_MARKDOWN_ALLOW_UNSAFE_CONTENT,
  block_external: process.env.INSTANT_MARKDOWN_BLOCK_EXTERNAL,
}

require('./index.js')(opts)
